интеграционное тестирование
armidsinner/qna pull request #3
Opened 2021-09-03 08:09 UTC by armidsinner

1. Реализовать следующие истории, начиная с acceptance-тестов (если они уже реализованы, покрыть acceptance-тестами):
  - Пользователь может создавать вопрос
  - Пользователь может просматривать список вопросов
  - Пользователь, находясь на странице вопроса, может написать ответ на вопрос (т.е. форма нового ответа должна быть прямо на странице вопроса, без перехода на другую страницу)
  - Пользователь может просматривать вопрос и ответы к нему.

 2. Добавить аутентификацию к проекту, покрыть acceptance-тестами следующие сценарии:
  - Пользователь может войти в систему
  - Пользователь может выйти из системы
  - Пользователь может зарегистрироваться в системе

 3. Реализовать следующие истории:
  - Только аутентифицированный пользователь может создавать вопросы и ответы
  - Автор может удалить свой вопрос или ответ, но не может удалить чужой вопрос/ответ

2021-09-03 12:44 UTC, vkurennov requested changes

2021-09-03 12:44 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      redirect_to @question
нельзя делать редирект в случае ошибок валидации, т.к. так потеряется информация об ошибках и то, что ввел пользователь. надо делать рендер той страницы, с которой отправлялась форма, в данном случае -  questions/show

2021-09-03 12:44 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  def new; end
форма ответа на странцие вопроса, отдельный экшн new здесь не нужен

2021-09-03 12:44 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      flash[:notice] = 'Oooops something went wrong((('
этого недостаточно, надо выводить полную информацию об ошибках валидации и делать это не через флеш, а на странице через паршл ошибок, а чтобы он работал, как раз и нужен рендер, а не редирект

2021-09-03 12:44 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @answer = Answer.find(params[:id])
у тебя уже вызыватся load_answer, который делает то же самое

2021-09-03 12:44 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  def check_author(resourse)
такая проверка нужна будет не только в контроллерах, лучше вынести ее в метод `User#author_of` и вызывать этот метод там, где нужно. и не забудь тесты модели на этот метод

2021-09-03 12:44 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    if check_author(@question)
замени на метод  `User#author_of?`

2021-09-03 12:44 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +  def check_author(resourse)
видишь, у тебя дублируется этот метод, что говорит о том, что вбыранный подход не лучший. вынеся проверку в метод модели, у тебя будет только одна точка изменений - сам этот метод в одном месте. если изменится логика проверки, ты лишь поменяешь код одного метода и он по всему остальному коду начнет работать по-новому. вот почему дублирование плохо - нексолько точек изменений и двойная работа

2021-09-03 12:44 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    params.require(:answer).permit(:body, :user_id)
user_id не должен передаваться в параметрах, его надо в экшене устанавливать через current_user, иначе можно передать любой user_id и создать ответ от любого юзера

2021-09-03 12:44 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    params.require(:question).permit(:title, :body, :user_id)
user_id не передается в параметрах, а устанавливается в экшенах через current_user

2021-09-03 12:44 UTC, vkurennov commented on app/models/answer.rb
> +<<<<<<< HEAD
приехали. у тебя конфликт изменений, ты залил неисправленный код. ты его хоть запускал? он же не загрузится. внеси исправления и закоммить их

2021-09-03 12:44 UTC, vkurennov commented on app/models/question.rb
> +<<<<<<< HEAD
снова конфликт изменений. конфликты нельзя просто игнорировать, они специално вносят правки, которые сломают код, чтобы случайно не залить. у тебя здесь показаны 2 конфликтующие части, надо оставить только нужный код и удалить все, что внес гит (все эти <<<, ===, >>>  и т.п.)

2021-09-03 12:44 UTC, vkurennov commented on app/views/answers/_answer.html.erb
> +<tr>
в этой части мы используем slim, а не erb, переведи все виды на slim

2021-09-03 12:44 UTC, vkurennov commented on app/views/answers/_form.html.erb
> +    <%= form.hidden_field :user_id, value: current_user.id  %>
очень плохое решение, т.к. можно окрыть код страницы и подставить произвольный user_id, создав ответ от другого пользователя.

2021-09-06 18:58 UTC, VidgarVii requested changes

2021-09-06 18:58 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    @question.user = current_user
это бесполезная операция. Так как автор вопроса у тебя устанавливается на 28 строке

2021-09-06 18:58 UTC, VidgarVii commented on app/views/questions/_form.html.slim
> += form_with model: @question, local: false do |form|
прочти примечание

2021-09-06 18:58 UTC, VidgarVii commented on app/views/devise/registrations/edit.html.erb
> +<h2>Edit <%= resource_name.to_s.humanize %></h2>
нет смысла создавать файлы devise если ты их не переопределяешь

2021-09-06 18:58 UTC, VidgarVii commented on spec/features/question/show_spec.rb
> +      end
итерации в тестах всегда плохо.
Если тест упадёт внутри блока, то сложно будет узнать, что именно упало
можно просто написать проверку на наличие текста, и сразу указать, что он встречается 3 раза

2021-09-06 18:58 UTC, VidgarVii commented on app/views/answers/_answer.html.slim
> +  p = link_to 'Delete', answer_path(answer),
ссылку на удаление можно показывать только автору. Ив тестах проверять что для не автора ссылки нет

2021-09-06 18:58 UTC, VidgarVii commented on app/views/answers/_answer.html.slim
> +- if answer.body.present?
зачем это проверять, если у нас есть валидация validates :body, presence ?

2021-09-06 18:58 UTC, VidgarVii commented on spec/models/user_spec.rb
> +  end
лучше указать 2 контекста. 
1 когда автор
2 когда не автор

2021-09-06 18:58 UTC, VidgarVii commented on app/controllers/answers_controller.rb
> +      redirect_to @answer.question
тут не обязательно делать редирект. хватит рендера. А лучшим вариантов отдавать статус forbidden

2021-09-06 18:58 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +      redirect_to @question
тоже самое что и у ответа

2021-09-06 18:58 UTC, VidgarVii commented on app/controllers/answers_controller.rb
> +  before_action :load_answer, only: :destroy
уже много раз обсуждалось что для 1 экшена колбеки не пишут

2021-09-06 18:58 UTC, VidgarVii commented on app/controllers/answers_controller.rb
> +      flash[:notice] = 'Good job!'
старайся писать redirect_to последней операцией

2021-09-07 09:27 UTC, VidgarVii commented on app/views/answers/_answer.html.slim
> +- if answer.id.present?
логичней проверять статус персистентности объекта, а не его id
https://apidock.com/rails/ActiveRecord/Persistence/persisted%3F

2021-09-07 09:27 UTC, VidgarVii commented on app/views/answers/_answer.html.slim
> +  - if current_user.present? && current_user.check_author?(answer)
можно сократить проверку 
if current_user&.check_author?(answer)

2021-09-07 09:27 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +      render @question
зачем что-то обновлять на странице если операция не возможна. Я уже писал вышел. Достаточно отправить статус запроса forbidden
head :forbidden
в контроллере ответов тоже самое

2021-09-07 21:15 UTC, merged